package Java.tasks;

import java.util.Arrays;
import java.util.Random;

public class FindTheDifference {

    public static void main(String[] args) {


        /*
        you are given two string s and t
        string t is generated by random shuffling string s and then add one more letter at a random position
        Return the letter that ws added to t
         */

        String s = "abc";
        String t = "aebc";


        char[] array1 = s.toCharArray();
        char[] array2 = t.toCharArray();

        boolean found = false;
        char differentCharacter = '\0';

// Determine the minimum length between the two arrays
        int minLength = Math.min(array1.length, array2.length);

        for (int i = 0; i < minLength; i++) {
            if (array1[i] != array2[i]) {
                found = true;
                differentCharacter = array2[i];
                break;
            }
        }

// If the arrays have different lengths, consider the additional characters in the longer array
        if (!found && array1.length < array2.length) {
            differentCharacter = array2[array1.length];
            found = true;
        }

        if (found) {
            System.out.println("The different character is: " + differentCharacter);
        } else {
            System.out.println("The two arrays are the same.");
        }



    }

}